### ISSUE TITLE
Calibration with more than 101 points

### ISSUE THREAD

**Issue by josalggui** [PICC-Group/pynanovna#11]
Hi guys,

Nice to see the new version. Do you know if it is possible to calibrate with more than 101 points?

**Comment by tbergkvist** [comment]
Hi! 
It should be possible to calibrate with any number of points supported by the NanoVNA.
Set the sweep to the desired frequency range and number of points before you calibrate.

As you said, the possible number of points vary between NanoVNA types, but as long as the number of points are chosen according to that it should be ok.

Have you had any issues with calibrating with other than 101 points?

Thank you for using pynanovna and for contributing with issues, it means a lot! :)

**Comment by tbergkvist** [comment]
I tried calibrating with 1001 points on my LiteVNA (it's a V2) using the example_calibration.py script and it worked well.
Right now I only have access to this machine so I cannot test on another but if you have trouble, please provide information on what NanoVNA you use and the code that fails.

**Comment by josalggui** [comment]
NanoVNA-H, that allows up to 101 points. So I my issue is in the versions of the NanoVNA. Understood!
